Aruuz.Website/Controllers/ExamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aruuz.Models;
using MySql.Data.MySqlClient;
using System.Text.RegularExpressions;
using Aruuz.Models;

namespace Aruuz.Controllers
{
    public class ExamplesController : Controller
    {
        //
        // GET: /Examples/
        MySqlConnection myConn;
        MySqlDataReader dataReader;
        string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["mySqlConnection"].ConnectionString;

        public ActionResult Index(int? page)
        {
            List<Poetry> pt = new List<Poetry>();
            MySqlConnection myConn;
            MySqlDataReader dataReader;
            myConn = new MySqlConnection(TaqtiController.connectionString);
            myConn.Open();
            MySqlCommand cmd = new MySqlCommand(TaqtiController.connectionString);
            cmd = myConn.CreateCommand();
            int maxCount = 1;
            int maxPages = 1;
            int residue = 0;
            cmd.CommandText = "select count(id) from Poetry;";
            dataReader = cmd.ExecuteReader();
            while (dataReader.Read())
            {
                maxCount = dataReader.GetInt32(0);
            }
            myConn.Close();
            maxPages = maxCount / 15;
            residue = maxCount - maxPages * 15;
            if (residue > 0)
            {
                maxPages = maxPages + 1;
            }
            if (page == null || page == 1)
            {
                MySqlConnection myConn2;
                MySqlDataReader dataReader2;
                myConn2 = new MySqlConnection(TaqtiController.connectionString);
                myConn2.Open();
                MySqlCommand cmd2 = new MySqlCommand(TaqtiController.connectionString);
                cmd2 = myConn2.CreateCommand();
                cmd2.CommandText = "select * from Poetry order by id DESC limit 0,15";
                dataReader2 = cmd2.ExecuteReader();
                int typeId = -1; ;
                while (dataReader2.Read())
                {
                    Poetry p = new Poetry();
                    p.id = dataReader2.GetInt32(0);
                    p.poet = dataReader2.GetString(1);
                    p.title = dataReader2.GetString(2);
                    p.text = dataReader2.GetString(4);
                    typeId = dataReader2.GetInt32(3);
                    p.meters = dataReader2.GetString(5);
                    if (typeId == 0)
                    {
                        p.type = "غزل";
                    }
                    else if (typeId == 1)
                    {
                        p.type = "نظم";
                    }
                    else if (typeId == 2)
                    {
                        p.type = "رباعی";
                    }
                    else if (typeId == 3)
                    {
                        p.type = "قطعہ";
                    }
                    else if (typeId == 4)
                    {
                        p.type = "آزاد نظم";
                    }
                    else if (typeId == 5)
                    {
                        p.type = "شعر";
                    }
                    p.maxpages = maxPages;
                    p.currentPage = 1;
                    pt.Add(p);
                }
                myConn2.Close();

            }
            else
            {
                MySqlConnection myConn2;
                MySqlDataReader dataReader2;
                myConn2 = new MySqlConnection(TaqtiController.connectionString);
                myConn2.Open();
                MySqlCommand cmd2 = new MySqlCommand(TaqtiController.connectionString);
                cmd2 = myConn2.CreateCommand();
                cmd2.CommandText = "select * from Poetry order by id DESC limit @init,@count";
                if (page == maxPages && residue > 0)
                {
                    cmd2.Parameters.AddWithValue("@init", (page - 1) * 15);
                    cmd2.Parameters.AddWithValue("@count", residue);
                }
                else
                {
                    cmd2.Parameters.AddWithValue("@init", (page - 1) * 15);
                    cmd2.Parameters.AddWithValue("@count", 15);
                }
               
                dataReader2 = cmd2.ExecuteReader();
                int typeId = -1; ;
                while (dataReader2.Read())
                {
                    Poetry p = new Poetry();
                    p.id = dataReader2.GetInt32(0);
                    p.poet = dataReader2.GetString(1);
                    p.title = dataReader2.GetString(2);
                    typeId = dataReader2.GetInt32(3);
                    p.text = dataReader2.GetString(4);
                    p.meters = dataReader2.GetString(5);
                    if (typeId == 0)
                    {
                        p.type = "غزل";
                    }
                    else if (typeId == 1)
                    {
                        p.type = "نظم";
                    }
                    else if (typeId == 2)
                    {
                        p.type = "رباعی";
                    }
                    else if (typeId == 3)
                    {
                        p.type = "قطعہ";
                    }
                    else if (typeId == 4)
                    {
                        p.type = "آزاد نظم";
                    }
                    else if (typeId == 5)
                    {
                        p.type = "شعر";
                    }
                    p.maxpages = maxPages;
                    p.currentPage = (int)page;
                    pt.Add(p);
                }
                myConn2.Close();
            }
            return View(pt);

        }
        public ActionResult Poets(string poet)
        {
            List<Poetry> pt = new List<Poetry>();
            MySqlConnection myConn;
            MySqlDataReader dataReader;
            myConn = new MySqlConnection(TaqtiController.connectionString);
            myConn.Open();
            MySqlCommand cmd = new MySqlCommand(TaqtiController.connectionString);
            cmd = myConn.CreateCommand();
            if (poet.Equals("غالب"))
            {
                cmd.CommandText = "select * from Poetry where poet like '" + "اسد اللہ خان غالب" + "' order by secid";
            }
            else
            {
                cmd.CommandText = "select * from Poetry where poet like '" + poet + "' order by secid";

            }
            dataReader = cmd.ExecuteReader();
            int typeId = -1; 
            while (dataReader.Read())
            {
                Poetry p = new Poetry();
                p.id = dataReader.GetInt32(0);
                p.poet = dataReader.GetString(1);
                p.title = dataReader.GetString(2);
                typeId = dataReader.GetInt32(3);
                p.meters = dataReader.GetString(5);
                if (typeId == 0)
                {
                    p.type = "غزل";
                }
                else if (typeId == 1)
                {
                    p.type = "نظم";
                }
                else if (typeId == 2)
                {
                    p.type = "رباعی";
                }
                else if (typeId == 3)
                {
                    p.type = "قطعہ";
                }
                else if (typeId == 4)
                {
                    p.type = "آزاد نظم";
                }
                else if (typeId == 5)
                {
                    p.type = "شعر";
                }

                pt.Add(p);
            }
            myConn.Close();


            return View(pt);
        }
        public ActionResult Filter()
        {
            List<Poets> pt = new List<Poets>();
            MySqlConnection myConn;
            MySqlDataReader dataReader;
            myConn = new MySqlConnection(TaqtiController.connectionString);
            myConn.Open();
            MySqlCommand cmd = new MySqlCommand(TaqtiController.connectionString);
            cmd = myConn.CreateCommand();
            cmd.CommandText = "select distinct poet from Poetry;";
            dataReader = cmd.ExecuteReader();
            Poets p2 = new Poets();
            p2.poet = "تمام";
            pt.Add(p2);
            while (dataReader.Read())
            {
                Poets p = new Poets();
                p.poet = dataReader.GetString(0);
                pt.Add(p);
            }
           
            myConn.Close();

            foreach (var p in pt)
            {
                using (MySqlConnection connection = new MySqlConnection(TaqtiController.connectionString))
                {
                    connection.Open();
                    using (MySqlCommand command = connection.CreateCommand())
                    {
                        if (p.poet.Equals("تمام")) {
                            command.CommandText = "select distinct type from Poetry;";
                        }
                        else
                        {
                            command.CommandText = "select distinct type from Poetry where poet like @poet;";
                            command.Parameters.AddWithValue("@poet", p.poet);
                        }
                        using (MySqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                int typeId;
                                typeId = reader.GetInt32(0);
                                if (typeId == 0)
                                {
                                    p.types.Add("غزل");
                                }
                                else if (typeId == 1)
                                {
                                   p.types.Add("نظم");
                                }

Aruuz.Website/Controllers/ResourcesController.cs
using Aruuz.Controllers;
using Aruuz.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aruuz.Website.Controllers
{
    public class ResourcesController : Controller
    {
        //
        // GET: /Resources/
        public ActionResult Index()
        {
            List<Resources> pt = new List<Resources>();
            MySqlConnection myConn;
            MySqlDataReader dataReader;
            myConn = new MySqlConnection(TaqtiController.connectionString);
            myConn.Open();
            MySqlCommand cmd = new MySqlCommand(TaqtiController.connectionString);
            cmd = myConn.CreateCommand();
            cmd.CommandText = "select * from Resources order by date DESC";
            dataReader = cmd.ExecuteReader();
            while (dataReader.Read())
            {
                Resources p = new Resources();
                p.id = dataReader.GetInt32(0);
                p.title = dataReader.GetString(1);
                p.text = dataReader.GetString(2);
                p.author = dataReader.GetString(3);
                p.date = dataReader.GetDateTime(4);
                p.category = dataReader.GetString(5);
                p.website = dataReader.GetString(6);
                pt.Add(p);
            }
            myConn.Close();


            return View(pt);
        }
        public ActionResult Article(int id)
        {
            Resources pt = new Resources();
            MySqlConnection myConn;
            MySqlDataReader dataReader;
            myConn = new MySqlConnection(TaqtiController.connectionString);
            myConn.Open();
            MySqlCommand cmd = new MySqlCommand(TaqtiController.connectionString);
            cmd = myConn.CreateCommand();
            cmd.CommandText = "select * from Resources where id = @id;";
            cmd.Parameters.AddWithValue("@id",id);
            dataReader = cmd.ExecuteReader();
            while (dataReader.Read())
            {
                pt.id = dataReader.GetInt32(0);
                pt.title = dataReader.GetString(1);
                pt.text = dataReader.GetString(2);
                pt.author = dataReader.GetString(3);
                pt.date = dataReader.GetDateTime(4);
                pt.category = dataReader.GetString(5);
                pt.website = dataReader.GetString(6);
                pt.keywords = dataReader.GetString(7);
            }
            myConn.Close();
            return View(pt);
        }
        public ActionResult MetersList()
        {
            List<MetersList> lst = findMeter.findMeters();
            return View(lst);
        }
	}
}

Aruuz.Website/Views/Resources/Article.cshtml
@model Aruuz.Models.Resources
           @using System.Globalization

@{
    ViewBag.Title = Model.title;
    Layout = "~/Views/Shared/_Layout.BootstrapEditorTemplates.cshtml";
}

<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<style scoped>
    .white {
        color:  #00ff21;
    }
</style>
<style scoped>
    .fb-comments, .fb-comments span, .fb-comments.fb_iframe_widget span iframe {
        width: 100% !important;
    }
</style>

@section meta{
    <meta name="description" content="Free Articles about Urdu Poetry" />
    <meta name="description" content="اردو شاعری اور علم عروض پر مضامین" />
    <meta name="keywords" content="@Model.keywords" />
    <meta name="author" content="@Model.author" />
    <meta name="image" content="/images/aruuz3.jpg" />
    <meta property="fb:admins" content="sayedzeeshan.asghar" />
    <meta property="fb:app_id" content="202167263310439" />
    <meta property="og:type" content="aruuztaqti:poetry" />
    <meta property="og:title" content="@Model.title" />
    <meta property="og:image" content="/images/aruuz3.jpg" />
    <meta property="og:description" content="@Model.title" />
    }




<div class="container" dir="rtl">
    <ol class="breadcrumb urdu">
        <li><a href="/Resources">مضامین</a></li>
        <li><a href="#">@Model.category</a></li>
    </ol>
    <div class="row">
        <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading panel-primary">
                    <img src="~/icons/articles.png" width="50" height="50" class="pull-left">

                    <div class="urdu-huge">
                        @Model.title
                    </div>
                    <div class="urdu">از <a class="white" href="@Model.website">@Model.author</a></div>


                </div>
                <div class="panel-body urdu">
                    @Html.Raw(@Model.text)


                    <hr>
                    <br>
                    @{
                        @*string url = "http://www.aruuz.com" + Request.RawUrl;

                            <div class="fb-comments img-responsive" data-href="@url" data-width="900" data-numposts="15" data-colorscheme="light"></div>*@
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'aruuz'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function () {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
}
                </div>
                <div class="panel-footer panel-info urdu">
                    بتاریخ 
                    @Model.date.ToString("d MMMM، yyy", CultureInfo.CreateSpecificCulture("ur-PK"))




                </div>

            </div>

        </div>
    </div>
</div>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
  m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-46123045-1', 'aruuz.com');
    ga('send', 'pageview');

</script>

Aruuz.Website/Views/Resources/Index.cshtml
@model IEnumerable<Aruuz.Models.Resources>
           @using System.Globalization
@{
    
    ViewBag.Title = "عروض، شاعری اور ویب سائٹ کے استعمال پر مضامین";
    Layout = "~/Views/Shared/_Layout.BootstrapEditorTemplates.cshtml";

}

@section meta{
    <meta name="description" content="Free Articles on Urdu Poetry">
    <meta name="description" content="اردو شاعری اور علم عروض پر مضامین">
    <meta name="author" content="Sayed Zeeshan Asghar">
    <meta property="fb:admins" content="sayedzeeshan.asghar" />
}




<div id="metersDiv"></div>

<div class="urdu">
    <div class="container" dir="rtl">
        <div class="row">
            <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-primary">
                    <img src="~/icons/articles.png" width="50" height="50" class="pull-left">

                    <div class="panel-heading">
                        <p class="urdu-huge">مضامین</p>
                        <p class="urdu-large">ویب سائٹ کے استعمال، عروض اور شاعری سے متعلق مضامین</p>
                    </div>

                    <div class="panel-body">
                        <table class="table urdu table-striped table-bordered">
                            <tr class="success">
                                <td>عنوان</td>
                                <td>مصنف</td>
                                <td>زمرہ</td>
                                <td>تاریخ</td>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    @if (item.id == 17)
                                    {
                                        <td>
                                            @Html.ActionLink(item.title, "MetersList", "Resources")
                                        </td>
                                        <td>
                                            <a href="@item.website">@Html.DisplayFor(modelItem => item.author)</a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.category)
                                        </td>
                                        <td>
                                            @item.date.ToString("d MMMM، yyy",CultureInfo.CreateSpecificCulture("ur-PK"))
                                        </td>
                                    }
                                    else
                                    {
                                        <td>
                                            @Html.ActionLink(item.title, "Article", "Resources", new { id = item.id }, null)
                                        </td>
                                        <td>
                                            <a href="@item.website">@Html.DisplayFor(modelItem => item.author)</a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.category)
                                        </td>
                                        <td>
                                            @item.date.ToString("d MMMM، yyy", CultureInfo.CreateSpecificCulture("ur-PK"))


                                        </td>
                                    }
                                </tr>
                            }
                        </table>


                    </div>
                    <div class="panel-footer">


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
  m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-46123045-1', 'aruuz.com');
    ga('send', 'pageview');

</script>

Aruuz.Website/Views/Resources/MetersList.cshtml
@model IEnumerable<MetersList>
@using Aruuz.Models

@{
    ViewBag.Title = "بحور کی فہرست";
    Layout = "~/Views/Shared/_Layout.BootstrapEditorTemplates.cshtml";
}

<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<style>
    .white {
        color:  #00ff21;
    }
</style>

@section meta{
    <meta name="description" content="Free Articles about Urdu Poetry">
    <meta name="description" content="اردو شاعری اور علم عروض پر مضامین">
    <meta name="keywords" content="عروض، اردو شاعری، شاعری، بحور، بحور فہرست، بحر ہزج، بحر رمل، بحر متقارب، میر ہندی بحر، بحر ہندی، بحر رمزمہ، متدارک بحر">
    <meta name="author" content="Sayed Zeeshan Asghar">
    <meta property="fb:admins" content="sayedzeeshan.asghar" />
}




<style>
    .fb-comments, .fb-comments span, .fb-comments.fb_iframe_widget span iframe {
        width: 100% !important;
    }
</style>

<div class="urdu">
    <div class="container" dir="rtl">
        <ol class="breadcrumb urdu">
            <li><a href="/resources">مضامین</a></li>
            <li><a href="#">ویب سائٹ</a></li>
        </ol>
        <div class="row">
            <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading panel-primary">
                        <img src="~/icons/articles.png" width="50" height="50" class="pull-left">
                        <div class="urdu-huge">
                           عروض سائٹ پر موجود کلام کے بحور کی فہرست
                        </div>
                        <div class="urdu">از <a class="white" href="https://twitter.com/sayed_asghar">سید ذیشان اصغر</a></div>
                    </div>
                    <div class="panel-body urdu">
                        <table class="table table-striped table-bordered urdu-naskh">
                            <tr class="success" id="main">
                                <td>بحر</td>
                                <td>بنیادی وزن</td>
                            </tr>
                            @{int i = 1;}
                            @foreach (var item in Model)
                            {
                                string url1 = "/examples/meter=?" + item.ToString();
                                List<int> lst = Meters.meterIndex(item.name.Trim());
                                string Afail = "";
                                if (lst.Count > 0)
                                {
                                    Afail = Meters.Afail(Meters.meters[lst.First()]);
                                }
                                else
                                {
                                    Afail = Meters.AfailHindi(item.name);
                                }

                                <tr>
                                    <td>
                                      @Html.ActionLink(item.name, "Meters", "Examples", new { meter = item.name.Replace("/", "_")},null)  <span class="badge alert-danger">@Html.DisplayFor(modelItem => item.count) </span>
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => Afail)
                                    </td>
                                </tr>
                               i = i + 1;

                            }
                        </table>
                        @{
                            <div id="disqus_thread"></div>
                            <script type="text/javascript">
                                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                                var disqus_shortname = 'aruuz'; // required: replace example with your forum shortname

                                /* * * DON'T EDIT BELOW THIS LINE * * */
                                (function () {
                                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                                })();
                            </script>
                            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            @*string url = "http://www.aruuz.com" + Request.RawUrl;

                           <div class="fb-comments img-responsive" data-href="@url" data-width="900" data-numposts="15" data-colorscheme="light"></div>*@
                        }
                    </div>
                    <div class="panel-footer panel-info urdu">
                        بتاریخ @{var date = "18-9-2014";}
                        @date
                    </div>

                </div>

               

            </div>
        </div>
    </div>
</div>


<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
  m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-46123045-1', 'aruuz.com');
    ga('send', 'pageview');

</script>